# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Canopy < Formula
  desc "CLI for Canopy mobile app policy compliance scanner"
  homepage "https://github.com/hha-nguyen/canopy-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hha-nguyen/canopy-cli/releases/download/v1.0.0/canopy-darwin-amd64.tar.gz"
      sha256 "e60e798ab73c7cf1a925897291a1c24c21445a8a486e012a87645f8f7161b455"

      def install
        bin.install "canopy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hha-nguyen/canopy-cli/releases/download/v1.0.0/canopy-darwin-arm64.tar.gz"
      sha256 "e8f214730563aa24f0c5a65774dfab8e415f2cb65996819740f2b9ddf41f79c6"

      def install
        bin.install "canopy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hha-nguyen/canopy-cli/releases/download/v1.0.0/canopy-linux-amd64.tar.gz"
      sha256 "2928338105462970cec7cad43656643c5df329dc0ef10a1df4d65a555a26bb32"
      def install
        bin.install "canopy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hha-nguyen/canopy-cli/releases/download/v1.0.0/canopy-linux-arm64.tar.gz"
      sha256 "4d44ced26e6c8a2db63e4fc73d41bf06855b34be8e77b4545d438a71b57c9053"
      def install
        bin.install "canopy"
      end
    end
  end

  test do
    system "#{bin}/canopy", "version"
  end
end
